### ISSUE TITLE
Adding ability to look up team.roster by week.

### ISSUE THREAD

**Issue by jimweigandt** [whatadewitt/yahoo-fantasy-sports-api#73]
Is there any update on being able to pull in team.roster by week at all? It looks like there is a TODO on the sandbox site - `TODO: add support for the "week" parameter`

Or maybe at least a work-around. I have not had much luck lately.

Appreciate you putting this package together! It's an awesome project.

**Comment by whatadewitt** [comment]
Let me look into this, it might not be a huge lift.

**Comment by whatadewitt** [comment]
Uh... so this might actually work and is just a hole in my documentation... but if you simply specify a week, instead of a date, I fall back to using the week...

You can use team_key: mlb.l.5208.t.1 and date: 3 at https://yahoo-fantasy-node-docs.vercel.app/resource/roster/players to see this in action... my league (5208) is public, so you don't need to auth. Let me know if that's what you're looking for and I can update the docs!

**Comment by whatadewitt** [comment]
I updated the docs roster.players and removed the TODO from team.roster. I hope that this helps you!!

**Comment by jimweigandt** [comment]
I never got back to you on this but thanks for the response on this! Using that optional parameter is exactly what I was looking for.

The only thing I wish that Yahoo would change about their API is not updating what teams certain players were on. Only takes in account for their current or most recently played team!
